server:
  port: 10010
spring:
  application:
    name: server-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers: #覆盖默认敏感头信息，配置禁止使用的头信息，这里设置为null,否则set-cookie无效
leyou:
  jwt:
    pubKeyPath: F:\\ideawork\\leyoumall\\tmp\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
