server:
  port: 8089

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/leyou?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456a
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 192.168.91.128
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: leyou.item.exchange
    publisher-confirms: true
  redis:
    host: 192.168.91.128
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

leyou:
  worker:
    workerId: 1 #为了保证不重复，我们给每个部署的节点都配置机器id
    datacenterId: 1
  jwt:
    pubKeyPath: F:\\ideawork\\leyoumall\\tmp\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
